### ISSUE TITLE
TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by sarvesh610** [tan-tan-kanarek/node-soap-server#4]
Hi,
I am trying to use the sample code you have provided, but I keep getting an exception.
`        var args = matches[1].split(',');
                          ^

TypeError: Cannot read property '1' of null
    at new SoapOperation (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:35:20)
    at SoapService.addOperation (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:121:26)
    at new SoapService (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:116:9)
    at SoapServer.addService (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:154:24)
    at Object.<anonymous> (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\test-server.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

I am using the following code:
`        var args = matches[1].split(',');
                          ^

TypeError: Cannot read property '1' of null
    at new SoapOperation (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:35:20)
    at SoapService.addOperation (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:121:26)
    at new SoapService (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:116:9)
    at SoapServer.addService (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\node_modules\soap-server\lib\soap-server.js:154:24)
    at Object.<anonymous> (C:\Users\Sarvesh\OneDrive\projects\tririga-soap\test-server.js:9:30)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)`

Thank you

**Comment by tan-tan-kanarek** [comment]
This is a very old code, written using very old standard.
I recommend to review it and rewrite it using modern class structure and promises.
